Hw 5
vsdmitriy17/nodejs-homework-REST_API pull request #4
Opened 2022-12-07 15:43 UTC by vsdmitriy17

2022-12-08 13:55 UTC, Eastvarga requested changes
Є зауваження що до url

2022-12-09 12:24 UTC, vsdmitriy17 commented on homework_5/controllers/auth/avatarUpdate.js
> +        const avatarURL = path.join("avatars", newFileName); // новий шлях до ф-лу (аватрки)
Исправил

2022-12-09 16:44 UTC, Eastvarga requested changes
Є зауваження

2022-12-09 16:44 UTC, Eastvarga commented on homework_5/controllers/auth/avatarUpdate.js
> +        const avatarImg = path.join("avatar", newFileName); // новий шлях до ф-лу (аватрки)
Перейменування змінної не виправить те, що строка, котру  вона зберігає, не є URL
https://ru.wikipedia.org/wiki/URL

2022-12-09 16:44 UTC, Eastvarga commented on homework_5/models/user.js
> -        avatarURL: {
Навіщо перейменували? Поверніть поле відповідно ДЗ

2022-12-10 17:10 UTC, Eastvarga approved these changes

2022-12-10 17:10 UTC, merged